### ISSUE TITLE
BUG: forward modelling-NSEM

### ISSUE THREAD

**Issue by kashkoulimohammad** [simpeg/simpeg#1280] opened 2023-08-27 05:44 UTC
### Describe the issue:

Hi

I am trying to run an example 2d forward modeling of iris mt course 2022 and am faced with the below error.
How can I solve it?

Regards,
Mohammad

### Reproducable code example:

```python
f_te = sim_te.fields()
pred_te = sim_te.dpred(f=f_te)
f_tm = sim_tm.fields()
pred_tm = sim_tm.dpred(f=f_tm)
```

### Error message:

```shell
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[24], line 2
      1 f_te = sim_te.fields()
----> 2 pred_te = sim_te.dpred(f=f_te)
      3 f_tm = sim_tm.fields()
      4 pred_tm = sim_tm.dpred(f=f_tm)

File c:\users\mohammad\documents\iris-2020\iris-mt-course-2022-main\iris-mt-course-2022-main\simpeg\SimPEG\simulation.py:262, in BaseSimulation.dpred(self, m, f)
    260 for src in self.survey.source_list:
    261     for rx in src.receiver_list:
--> 262         data[src, rx] = rx.eval(src, self.mesh, f)
    263 return mkvc(data)

File c:\users\mohammad\documents\iris-2020\iris-mt-course-2022-main\iris-mt-course-2022-main\simpeg\SimPEG\electromagnetics\natural_source\receivers.py:323, in PointNaturalSource.eval(self, src, mesh, f, return_complex)
    311 def eval(self, src, mesh, f, return_complex=False):
    312     """
    313     Project the fields to natural source data.
    314 
   (...)
    320     :return: Evaluated data for the receiver
    321     """
--> 323     imp = self._eval_impedance(src, mesh, f)
    324     if return_complex:
    325         return imp

File c:\users\mohammad\documents\iris-2020\iris-mt-course-2022-main\iris-mt-course-2022-main\simpeg\SimPEG\electromagnetics\natural_source\receivers.py:158, in PointNaturalSource._eval_impedance(self, src, mesh, f)
    156         PH = self.getP(mesh, "CC")
    157     elif self.orientation == "yx":
--> 158         PE = self.getP(mesh, "CC")
    159         PH = self.getP(mesh, "Ex")
    160 top = PE @ e[:, 0]

File c:\users\mohammad\documents\iris-2020\iris-mt-course-2022-main\iris-mt-course-2022-main\simpeg\SimPEG\electromagnetics\natural_source\receivers.py:111, in PointNaturalSource.getP(self, mesh, projGLoc, field)
    101 """
    102 Returns the projection matrices as a
    103 list for all components collected by
   (...)
    108     Projection matrices are stored as a dictionary listed by meshes.
    109 """
    110 if mesh.dim < 3:
--> 111     return super().getP(mesh, projGLoc=projGLoc)
    112 if projGLoc is None:
    113     projGLoc = self.projGLoc

File c:\users\mohammad\documents\iris-2020\iris-mt-course-2022-main\iris-mt-course-2022-main\simpeg\SimPEG\survey.py:91, in BaseRx.getP(self, mesh, projGLoc)
     88 if (mesh, projGLoc) in self._Ps:
     89     return self._Ps[(mesh, projGLoc)]
---> 91 P = mesh.getInterpolationMat(self.locations, projGLoc)
     92 if self.storeProjections:
     93     self._Ps[(mesh, projGLoc)] = P

File ~\anaconda3\envs\em\lib\site-packages\discretize\utils\code_utils.py:306, in deprecate_method.<locals>.new_method(self, *args, **kwargs)
    301 message = (
    302     f"{class_name}.{old_name} has been deprecated, please use "
    303     f"{class_name}.{new_name}.{tag}"
    304 )
    305 if error:
--> 306     raise NotImplementedError(message.replace("deprecated", "removed"))
    307 else:
    308     warnings.warn(
    309         message,
    310         warn,
    311         stacklevel=2,
    312     )

NotImplementedError: TensorMesh.getInterpolationMat has been removed, please use TensorMesh.get_interpolation_matrix.
```

### Runtime information:

--------------------------------------------------------------------------------
  Date: Sun Aug 27 09:09:39 2023 Iran Standard Time

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.4 GiB
       Environment : Python

  Python 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]

            SimPEG : 0.17.0
        discretize : 0.9.0
       pymatsolver : 0.2.0
        vectormath : 0.2.2
        properties : 0.6.1
             numpy : 1.24.4
             scipy : 1.10.1
            cython : Module not found
           IPython : 8.12.2
        matplotlib : 3.5.2
        ipywidgets : 7.6.5
--------------------------------------------------------------------------------

**Comment by santisoler** [comment] 2023-08-28 20:33
Hi @kashkoulimohammad. Thanks for opening this issue.

The problem is coming from the fact that you're using the latest version of discretize (v0.9.0) with an older version of SimPEG (v0.17.0). SimPEG is trying to call the `TensorMesh.getInterpolationMat()` method, but it has already been deprecated from the version of discretize that you're using.

A solution would be to install a newer version of SimPEG. Installing SimPEG v0.18.0 would be enough to solve this issue: that release includes the commit that replaces the old `getInterpolationMat()` method for the new `get_interpolation_matrix()` one.

Hope it helps!

**Comment by lheagy** [comment] 2023-11-29 19:10
Thanks for your question @kashkoulimohammad. I will close this issue as there hasn't been any activity in a while. Feel free to re-open if you are still running into challenges

**Closed by lheagy** 2023-11-29 19:10 UTC
