### ISSUE TITLE
Update required on the SaveIteration directive.

### ISSUE THREAD

**Issue by domfournier** [simpeg/simpeg#1184] opened 2023-02-25 17:14 UTC
As reported by Nigel @ CGI on Slack
###########################

Hi! have been getting to know the code base and testing a few things.   We are experiencing an error when saving iteration Dict while using sparse norms. We used the example http://docs.simpeg.xyz/content/tutorials/03-gravity/plot_inv_1b_gravity_anomaly_irls.html .  And a change was made adding the line:
save_iteration = directives.SaveOutputDictEveryIteration(saveOnDisk=True)
It crashed with:
Traceback (most recent call last):
  File "/mnt/c/Work/simpeg/compact/tmp/plot_inv_1b_gravity_anomaly_irls.py", line 306, in <module>
    recovered_model = inv.run(starting_model)
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/utils/counter_utils.py", line 136, in wrapper
    out = f(self, *args, **kwargs)
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/inversion.py", line 114, in run
    self.m = self.opt.minimize(self.invProb.evalFunction, self.invProb.model)
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/utils/counter_utils.py", line 136, in wrapper
    out = f(self, *args, **kwargs)
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/optimization.py", line 397, in minimize
    self.doEndIteration(xt)
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/utils/counter_utils.py", line 116, in wrapper
    out = f(self, *args, **kwargs)
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/utils/code_utils.py", line 298, in wrapper
    return f(self, *args, **kwargs)
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/optimization.py", line 691, in doEndIteration
    self.callback(xt)
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/inversion.py", line 120, in _optCallback
    self.directiveList.call("endIter")
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/directives/directives.py", line 216, in call
    getattr(r, ruleType)()
  File "/home/miniconda3/lib/python3.9/site-packages/SimPEG/directives/directives.py", line 1685, in endIter
    iterDict["lps"] = self.reg.objfcts[0].norms[0][0]
TypeError: 'float' object is not subscriptable

**Comment by micmitch** [comment] 2023-02-27 19:41
Same issue as the one I reported last week in  #1180

**Comment by jcapriot** [comment] 2023-02-28 00:10
Closing as duplicate of #1180

**Closed by jcapriot** 2023-02-28 00:10 UTC
Labels: bug
