### ISSUE TITLE
Shift XY location on drapeTopo

### ISSUE THREAD

**Issue by domfournier** [simpeg/simpeg#972] opened 2021-02-24 20:05 UTC
https://github.com/simpeg/simpeg/blob/768c073813ac3ae6e16e9d367279dc79baa986fe/SimPEG/electromagnetics/static/utils/static_utils.py#L1971

@jcapriot Any reason why we are also shifting the XY, instead of just Z, for the TreeMesh?

**Comment by jcapriot** [comment] 2021-02-24 20:50
No idea, you wrote it that way!
Duplicate of #913

**Closed** 2021-02-24 20:51 UTC

**Comment by domfournier** [comment] 2021-02-24 21:05
I see @sgkang you were the last one touching it. Is there something we should worry about just shifting Z and not XY?

**Comment by jcapriot** [comment] 2021-02-24 21:48
It’s a matter of selecting the heights in the top cells. It takes a little thought to make it work properly, as a closest neighbor lookup through a kdtree won’t work all the time.

**Comment by jcapriot** [comment] 2021-02-24 21:52
#842 Was a bug related to this, which is where I thought it had came from.
